// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image4":
            case "Forest":return img`
ddddddddddddddddddddddddddddddddddd444444444444444444ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddd44444444444444444dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddd4444444444444444dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddd444444444444dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddd444444ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffdddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffdd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffff
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffff
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffff
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffff
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffff
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffff
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffff
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffff
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffff
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffff
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffff
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffff
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffff
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffff
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffff
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffff
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffff
dddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffff
dddffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffff
dddffdddddddddddddddddfffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffff
dddffddddddddddddddddffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffff
ddfffddddddddddddddddffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffff
ddffffdddddddddddddddfffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffff
ddffffddddddddddddddfffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffff
ddfffffdddddddddddddfffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffffff
dffffffddddddddddddfffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffffff
dffffffddddddddddddfffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffff
dfffffffdddddddddddfffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffff
dffffffffdddddddddfffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffff
dffffffffdddddddddfffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffffffff
ffffffffffddddddddfffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffffffff
ffffffffffdddddddfffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffffffff
ffffffffffdddddddfffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffff
fffffffffffdddddffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffff
fffffffffffdddddfffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffdddddddddfffffffffffffffffffffffff
fffffffffffddddffffffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffddddddddddddddddddddfffddddddddfffffffffffffffffffffffff
ffffffffffffdddffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffdddddddddddddddddddffffddddddffffffffffffffffffffffffff
ffffffffffffddffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddfffffdddddffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffddddddddddddddddddffffffdddfffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffdddddddddddddddffffffffdfffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffddfffffffffffffdddddddddfffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffddffffffffdddddddddfffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffdddddddddddddddddddfffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffddddddddddddddddfffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffdddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffddddddddddddddfffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffddddddddddddffdddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffdddddddddddffffddddddddddddddddddddddddddddddddddddddddddddfffffffffdffffffdddddddddddffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffddddddddddfffffdddddddddddddddddddddddddddddddddddddddddddfffffdfffdddffffdddddddddddffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffddddddddddffffffddddddddddddddddddddddddddddddddddddddddddfffffdfffddddddddddddddddddffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffddddddddfffffffddddddddddddddddddddddddddddddddddddddddddddddddffffdddddddddddddddddffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffddddddddffffffffddddddddddddddddddddddddddddddddddddddddddddddffffffffdddddddddddddfffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffdddddddfffffffffddddddddddddddddddddddddddddddddddddddddddddfffffffffffffdddddddddfffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffdddddddfffffffffdddddddddddddddddddddddddddddddddddddddddddffffffffffffffdddddddddfffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffdddddddfffffffffddddddddddddddddddddddfddddddddddddddddddffffffffffffffffddddddddffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffddddddfffffffffffdddddddddddddddddddddfdddddddddddddddddffffffdfffdddddddddddddddffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffddddddffffffffffffddddddddddddddddddddffddddddddddddddddfffffddfffddddddddddddddfffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffdddddfffffffffffffddddddddddddddddddfffddddddddddddddddffffdddffffdddddddddddddfffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffdddddffffffffffffffdddddddddddddddddffffdddddddddddddddddddddffffffddddddddddddfffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffddddffffffffffffffdddddddddddddddddffffdddddddddddddddddddfffffffffffdddddddddfffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffddddfffffffffffffffddddddddddddddddfffffddddddddddddddddffffffffffffffdddddddffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffddffffffffffffffffdddddddddddddddffffffdddddddddddddddfffffffffffffffddddddfffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffddfffffffffffffffffddddddddddddddffffffdddddddddddddddffffffffffdffffddddddfffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffdffffffffffffffffffddddddddddddddfffffffddddddddddddddfffdddffffdddddddddddfffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdddddddddddddfffffffddddddddddddddddddddfffdddddddddddffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddffffffffddddddddddddddddddddfffdddddddddddffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdddddddddfffffffffdddddddddddddddddddfffdddddddddddffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image1":
            case "ROZZUM_Front":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...............ffff.............
..............fbbbbf............
..............fbbbbf............
..............fb1b1f............
..............fbbbbf............
.........ffffffbbbbffffff.......
........fbbbbbbbbbbbbbbbcf......
........fbbbbbbbbbbbbbbccf......
........fbbbbbbbbbbbbbcccf......
........fbbfbbbbbbbbccfccf......
........fbbffbbbbbbbcffccf......
........fbbf.fbbbbbcf.fccf......
........fbbf.fbbbcccf.fccf......
........fbbf.fbbccccf.fccf......
........fbbf.fbcffccf.fccf......
.........ff..fbcf.ccf..ff.......
.............fccf.ccf...........
.............fccf.ccf...........
............fcccf.cccf..........
`;
            case "image6":
            case "ROZZUM_Front0":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...............ffff.............
..............fbbbbf............
..............fbbbbf............
..............fbbbbf............
..............fbbbbf............
.........ffffffbbbbffffff.......
........fcbbbbbbbbbbbbbbbf......
........fccbbbbbbbbbbbbbbf......
........fcccbbbbbbbbbbbbbf......
........fccfccbbbbbbbbfbbf......
........fccffcbbbbbbbffbbf......
........fccf.fcbbbbbf.fbbf......
........fccf.fcccbbbf.fbbf......
........fccf.fccccbbf.fbbf......
........fccf.fccffcbf.fbbf......
.........ff..fccf.cbf..ff.......
.............fccf.ccf...........
.............fccf.ccf...........
............fcccf.cccf..........
`;
            case "image2":
            case "myImage":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..............ffff..............
.............fbbbbf.............
.............fbbb1f.............
.............fbbbbf.............
.............fbbbbf.............
............ffffffff............
............fbfbbfbf............
............fbfbbfbf............
............fbfbbfbf............
............fbfbbfbf............
............fbfbbfbf............
............fbfbbfbf............
.............ffbbff.............
..............fbbf..............
..............fbbf..............
..............ffff..............
..............fbbf..............
..............fbbf..............
..............fbbbf.............
`;
            case "image5":
            case "myImage1":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..............ffff..............
.............fbbbbf.............
.............f1bbbf.............
.............fbbbbf.............
.............fbbbbf.............
............ffffffff............
............fbfbcfcf............
............fbfccfcf............
............fcfccfcf............
............fcfccfcf............
............fcfccfcf............
............fcfccfcf............
.............ffccff.............
..............fccf..............
..............fccf..............
..............ffff..............
..............fccf..............
..............fccf..............
.............fcccf..............
`;
            case "image7":
            case "ROZZUM_Front1":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...............ffff.............
..............5bbbbf............
..............f5bbbf............
..............fc1b1f............
.........ff5..fbbbbf...ff.......
........fbbf5ffbbbbfff1bbf......
........fb5b5bb5bb5b71b1cf......
........fbc5cbbbbb57bb1ccf......
........f1bb7bbb1bcbbb7c7f......
........1b1fb7b1b1bb5cfccf......
........f1cffb7c1cb5cffc5f......
........fbbf.fbbbbbcf.fccf......
........f5bf.f5b7c5cf.fc7f......
........fc5f.ffff.fff.f7cf......
.........ff..fccf.c1f..ff.......
............fcc5f.7ccf..........
`;
            case "image9":
            case "myImage2":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
............fff.................
...........feeef................
..........fffeef................
.........fddeeef................
..........fffef.................
............fef.................
............fef.................
............feffffff............
............fddddeeef...........
............fdddddefef..........
.............fcfffcff...........
.............fc..fcf............
............ffc.ffcf............
...........fccffccf.............
`;
            case "image10":
            case "empty DO NOT DELETE":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image8":
            case "ROZZUM_Front2":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
............ffff................
...........fbbbbf...............
...........fbbbbf...............
...........fb1b1f...............
...........fbbbbf...............
...........fbbbbf...............
............2.8.................
...........2..8.................
............2..8................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;
            case "image11":
            case "myImage4":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...........f....................
..........f4ff..................
.........f4444f.................
.........ff444ffffffffff........
.........f444444444444ddf.......
.........ff44444444444ddf.......
..........ff4ddddd44ffff........
............fcffffcf............
............fcf..fcf............
...........fccf.fccf............
`;
            case "image3":
            case "myImage0":return img`
ddddddd444444ddddddddddddddddddd
ddddddd444444ddddddddddddddddddd
dddddddd4444dddddddddddddddddddd
dddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddd
ddddddffdddddddddddddddfdddddddd
dddddfffddfddddddddddddfdfdddddd
dddddfffdffddddddddddddffddddddd
ddddfffffdfddddddddddddfdddffddd
dddffffffdffdddddddddfffdddfffdd
dddffffffdfddddddddddddfdfdffffd
ddfffffffffddddddddddddffdffffff
ddffffffffddddfddddddddfddffffff
dffffffffffddffdddddffffdfffffff
dffffffffffdffffdddfdddfdfffffff
fffffffffffffffffddddddfffffffff
ffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff
`;
            case "image12":
            case "ROZZUM_Front3":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...............22..8............
................2.8.............
.........ffffffbbbbfffff........
........fbbbbbbbbbbbbbb22.......
........fbbbbbbbbbbbbbb.........
........fbbbbbbbbbbbbbc.........
........fbbfbbbbbbbbcc..........
.........bbffbbbbbbbcf..........
.........8.2.fbbbbbcf...........
........8....fbbbcccf...........
.............fbbccccf...........
..............bcffccf...........
.............2..8.ccf...........
...............8..ccf...........
...............8..ccf...........
..................cccf..........
`;
            case "image13":
            case "ROZZUM_Front4":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...............ffff.............
..............fbbbbf............
..............fbbbbf............
..............fb1b1f............
..............fbbbbf............
.........ffffffbbbbffffff.......
........fbbbbbbbbbbbbbbbcf......
........fbbbbbbbbbbbbbbccf......
........fbbbbbbbbbbbbbcccf......
........fbbfbbbbbbbbccfccf......
........fbbffbbbbbbbcffccf......
........fbbf.fbbbbbcf.fccf......
........fbbf.fbbbcccf.fccf......
........fbbf.fbbccccf.fccf......
........fbbf.fbcffccf.fccf......
.........ff..fbcf.ccf..ff.......
.............fccf.ccf...........
.............fccf.ccf...........
............fcccf.cccf..........
`;
            case "image14":
            case "myImage3":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image15":
            case "ROZZUM_Front5":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...........ffff.................
..........fbbbbf................
..........fbbbbf................
..........fb2b2f................
..........fbbbbf......fffffffff.
.....ffffffbbbbfffffffddddddd2f.
....fbbbbbbbbbbbbbbbbfddddddd2f.
....fbbbbbbbbbbbbbbbbfddfdfffff.
....fbbbbbbbbbbbbbffffddfff.....
....fbbfbbbbbbbbccf...ff........
....fbbffbbbbbbbcf..............
....fbbf.fbbbbbcf...............
....fbbf.fbbbcccf...............
....fbbf.fbbccccf...............
....fbbf.fbcffccf...............
.....ff..fbcf.ccf...............
.........fccf.ccf...............
.........fccf.ccf...............
........fcccf.cccf..............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
d d d d d d d d d d d d d d d d 
d d d d d 4 4 4 d d d d d d d d 
d d d d d 4 4 4 d d d d d d d d 
d d d d d 4 4 4 d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d f d d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d f f f f f d d d d d d d d d 
d d f f f f f f d d d d d d d d 
8 f f f f f f f f 8 8 8 8 8 8 8 
8 f f f f f f f f f 8 8 8 8 8 8 
f f f f f f f f f f f 8 8 8 8 8 
f f f f f f f f f f f f 8 8 8 8 
`, img`
d d d d d 4 4 4 d d d d d d d d 
d d d d d 4 4 4 d d d d d d d d 
d d d d d 4 4 4 d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d f d d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d f f f f f d d d d d d d d d 
d d f f f f f f d d d d d d d d 
d f f f f f f f f d d d d d d d 
8 f f f f f f f f f 8 8 8 8 8 8 
f f f f f f f f f f f 8 8 8 8 8 
f f f f f f f f f f f f 8 8 8 8 
f f f f f f f f f f f f f 8 8 8 
`, img`
d d d d d 4 4 4 d d d d d d d d 
d d d d d 4 4 4 d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d f d d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d f f f f f d d d d d d d d d 
d d f f f f f f d d d d d d d d 
d f f f f f f f f d d d d d d d 
d f f f f f f f f f d d d d d d 
f f f f f f f f f f f 8 8 8 8 8 
f f f f f f f f f f f f 8 8 8 8 
f f f f f f f f f f f f f 8 8 8 
f f f f f f f f f f f f f f 8 8 
`, img`
d d d d d 4 4 4 d d d d d d d d 
d d d d d 4 4 4 d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d f d d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d f f f f f d d d d d d d d d 
d d f f f f f f d d d d d d d d 
d f f f f f f f f d d d d d d d 
d f f f f f f f f f d d d d d d 
f f f f f f f f f f f 8 8 8 8 8 
f f f f f f f f f f f f 8 8 8 8 
f f f f f f f f f f f f f 8 8 8 
f f f f f f f f f f f f f f 8 8 
`, img`
d d d d d 4 4 4 d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d f d d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d f f f f f d d d d d d d d d 
d d f f f f f f d d d d d d d d 
d f f f f f f f f d d d d d d d 
d f f f f f f f f f d d d d d d 
f f f f f f f f f f f d d d d d 
f f f f f f f f f f f f 8 8 8 8 
f f f f f f f f f f f f f 8 8 8 
f f f f f f f f f f f f f f 8 8 
f f f f f f f f f f f f f f f 8 
`, img`
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d f d d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d d f f f d d d d d d d d d d 
d d f f f f f d d d d d d d d d 
d d f f f f f f d d d d d d d d 
d f f f f f f f f d d d d d d d 
d f f f f f f f f f d d d d d d 
f f f f f f f f f f f d d d d d 
f f f f f f f f f f f f d d d d 
f f f f f f f f f f f f f 8 8 8 
f f f f f f f f f f f f f f 8 8 
f f f f f f f f f f f f f f f 8 
f f f f f f f f f f f f f f f f 
`, img`
d d d 1 1 1 d 1 d 1 d 1 1 d d d 
d d d d 1 d d 1 1 1 d 1 d d 4 d 
d d d d 1 d d 1 d 1 d 1 1 d d d 
d 1 d 1 d 1 d 1 d 1 d d 1 1 d d 
d 1 d 1 d 1 d d d 1 d d 1 d 1 d 
d d 1 d 1 d d 1 d 1 1 d 1 1 d d 
d d d d d d d d d d d d d d d d 
1 1 d d 1 1 d 1 1 d d 1 1 d 1 1 
1 d 1 d 1 1 d 1 d 1 d 1 1 d d 1 
1 1 d d 1 1 d 1 1 d d 1 1 d d 1 
1 d 1 d 1 1 d 1 d 1 d 1 1 d d d 
d d d d d d d d 1 d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d b d d d d d d d d d d 
d d f f f f f f d d d d d d d d 
d f d d d d d d f f f f f f d d 
`, img`
d d d 1 1 1 d 1 d 1 d 1 1 d d d 
d d d d 1 d d 1 1 1 d 1 d d 4 d 
d d d d 1 d d 1 d 1 d 1 1 d d d 
d 1 d 1 d 1 d 1 d 1 d d 1 1 d d 
d 1 d 1 d 1 d d d 1 d d 1 d 1 d 
d d 1 d 1 d d 1 d 1 1 d 1 1 d d 
d d d d d d d d d d d d d d d d 
1 1 d d 1 1 d 1 1 d d 1 1 d 1 1 
1 d 1 d 1 1 d 1 d 1 d 1 1 d d 1 
1 1 d d 1 1 d 1 1 d d 1 1 d d 1 
1 d 1 d 1 1 d 1 d 1 d 1 1 d d d 
d d d d d d d d 1 d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d b d d d d d d d d d d 
d d f f f f f f d d d d d d d d 
d f d d d d d d f f f f f f d d 
`, img`
d d d 1 1 1 d 1 d 1 d 1 1 d d d 
d d d d 1 d d 1 1 1 d 1 d d 4 d 
d d d d 1 d d 1 d 1 d 1 1 d d d 
d 1 d 1 d 1 d 1 d 1 d d 1 1 d d 
d 1 d 1 d 1 d d d 1 d d 1 d 1 d 
d d 1 d 1 d d 1 d 1 1 d 1 1 d d 
d d d d d d d d d d d d d d d d 
1 1 d d 1 1 d 1 1 d d 1 1 d 1 1 
1 d 1 d 1 1 d 1 d 1 d 1 1 d d 1 
1 1 d d 1 1 d 1 1 d d 1 1 d d 1 
1 d 1 d 1 1 d 1 d 1 d 1 1 d d d 
d d d d d d d d 1 d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d b d d d d d d d d d d 
d d f f f f f f d d d d d d d d 
d f d d d d d d f f f f f f d d 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "song1":
            case "Boss battle":return hex`0078000408020400001c00010a006400f4016400000400000000000000000000000000050000044000040008000224250c00100001241000140002202a1400180001241c0020000124240028000224252c00300001243000340002202a3400380001243c004000012404001c00100500640000041e000004000000000000000000000000000a0000040c0010001400011d30003400011d06001c00010a006400f4016400000400000000000000000000000000000000020c000c00100001192c003000011907001c00020a006400f4016400000400000000000000000000000000000000030c00040008000120240028000120`;
            case "song2":
            case "theme":return hex`0078000408020200001c00010a006400f401640000040000000000000000000000000005000004420000000400012a04000800011b08000c00012210001400012a18001c0001221c002000012920002400012724002800011b28002c00012230003400012a38003c00012209010e02026400000403780000040a000301000000640001c80000040100000000640001640000040100000000fa0004af00000401c80000040a00019600000414000501006400140005010000002c0104dc00000401fa0000040a0001c8000004140005d0076400140005d0070000c800029001f40105c201f4010a0005900114001400039001000005c201f4010500058403050032000584030000fa00049001000005c201f4010500058403c80032000584030500640005840300009001049001000005c201f4010500058403c80064000584030500c8000584030000f40105ac0d000404a00f00000a0004ac0d2003010004a00f0000280004ac0d9001010004a00f0000280002d00700040408070f0064000408070000c80003c800c8000e7d00c80019000e64000f0032000e78000000fa00032c01c8000ee100c80019000ec8000f0032000edc000000fa0003f401c8000ea901c80019000e90010f0032000ea4010000fa0001c8000004014b000000c800012c01000401c8000000c8000190010004012c010000c80002c800000404c8000f0064000496000000c80002c2010004045e010f006400042c010000640002c409000404c4096400960004f6090000f40102b80b000404b80b64002c0104f40b0000f401022003000004200300040a000420030000ea01029001000004900100040a000490010000900102d007000410d0076400960010d0070000c8001200000001000102180019000100300031000102`;
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
